stages:
    - build
    - test
    - deploy

build:
    image: mcr.microsoft.com/dotnet/core/sdk:latest
    stage: build
    script:
        - cd src
        - dotnet build
    artifacts:
      paths:
        - src/Elpida.Backend/bin/
test:
    image: mcr.microsoft.com/dotnet/core/sdk:latest
    stage: test
    script: 
        - cd src
        - dotnet test

docker-build:
    # Official docker image.
    image: docker:latest
    stage: deploy
    services:
        - docker:dind
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    script:
        - docker build --pull -t "$CI_REGISTRY_IMAGE" .
        - docker push "$CI_REGISTRY_IMAGE"
    only:
        - master

docker-build-develop:
    # Official docker image.
    image: docker:latest
    stage: deploy
    services:
        - docker:dind
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    script:
        - docker build --pull -t "$CI_REGISTRY_IMAGE:develop" .
        - docker push "$CI_REGISTRY_IMAGE:develop"
    only:
        - develop
