stages:
    - build
    - test
    - deploy

build:
    image: mcr.microsoft.com/dotnet/sdk:5.0
    stage: build
    script:
        - cd src
        - dotnet build
    artifacts:
      paths:
        - src/Elpida.Backend/bin/
test:
    image: mcr.microsoft.com/dotnet/sdk:5.0
    stage: test
    script: 
        - cd src
        - dotnet test

.docker-image-build:
    image: docker:latest
    stage: deploy
    services:
        - docker:dind
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    script:
        - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_ENVIRONMENT_NAME" .
        - docker push "$CI_REGISTRY_IMAGE:$CI_ENVIRONMENT_NAME"

docker-image-build:production:
  extends: .docker-image-build
  environment:
    name: production
    url: https://api.elpida.dev
  only:
    - master

docker-image-build:staging:
  extends: .docker-image-build
  environment:
    name: staging
    url: https://staging.api.elpida.dev
  only:
    - staging
