image: mcr.microsoft.com/dotnet/core/sdk:latest

stages:
    - build
    - test

build:
    stage: build
    script:
        - "dotnet build"
    artifacts:
      paths:
        - bin/

build_image:
    script:
        - "docker build -t elpida-backend ."

test:
    stage: test
    script: 
        - "dotnet test"
