// <auto-generated />
using System;
using Elpida.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Elpida.Backend.Migrations
{
    [DbContext(typeof(ElpidaContext))]
    [Migration("20210325182342_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("BenchmarkModelTaskModel", b =>
                {
                    b.Property<long>("BenchmarksId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TasksId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BenchmarksId", "TasksId");

                    b.HasIndex("TasksId");

                    b.ToTable("BenchmarkModelTaskModel");
                });

            modelBuilder.Entity("Elpida.Backend.Data.Abstractions.Models.BenchmarkModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Benchmarks");
                });

            modelBuilder.Entity("Elpida.Backend.Data.Abstractions.Models.Cpu.CpuModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Caches")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Smt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cpus");
                });

            modelBuilder.Entity("Elpida.Backend.Data.Abstractions.Models.Result.ResultModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Affinity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("BenchmarkId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompilerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompilerVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ElpidaVersionBuild")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ElpidaVersionMajor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ElpidaVersionMinor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ElpidaVersionRevision")
                        .HasColumnType("INTEGER");

                    b.Property<double>("JoinOverhead")
                        .HasColumnType("REAL");

                    b.Property<double>("LockOverhead")
                        .HasColumnType("REAL");

                    b.Property<double>("LoopOverhead")
                        .HasColumnType("REAL");

                    b.Property<long>("MemorySize")
                        .HasColumnType("INTEGER");

                    b.Property<double>("NotifyOverhead")
                        .HasColumnType("REAL");

                    b.Property<double>("NowOverhead")
                        .HasColumnType("REAL");

                    b.Property<string>("OsCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OsName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OsVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PageSize")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SleepOverhead")
                        .HasColumnType("REAL");

                    b.Property<double>("TargetTime")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TopologyId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WakeupOverhead")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("BenchmarkId");

                    b.HasIndex("TopologyId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("Elpida.Backend.Data.Abstractions.Models.Result.TaskResultModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("InputSize")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MarginOfError")
                        .HasColumnType("REAL");

                    b.Property<double>("Max")
                        .HasColumnType("REAL");

                    b.Property<double>("Mean")
                        .HasColumnType("REAL");

                    b.Property<double>("Min")
                        .HasColumnType("REAL");

                    b.Property<long>("ResultId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SampleSize")
                        .HasColumnType("INTEGER");

                    b.Property<double>("StandardDeviation")
                        .HasColumnType("REAL");

                    b.Property<long?>("TaskId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Tau")
                        .HasColumnType("REAL");

                    b.Property<double>("Time")
                        .HasColumnType("REAL");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ResultId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskResultModel");
                });

            modelBuilder.Entity("Elpida.Backend.Data.Abstractions.Models.Task.TaskModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InputDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputName")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputProperties")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputUnit")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputName")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputProperties")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputUnit")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResultAggregation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResultType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultUnit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Elpida.Backend.Data.Abstractions.Models.Topology.TopologyModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CpuId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Root")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TopologyHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalDepth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalLogicalCores")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPhysicalCores")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CpuId");

                    b.ToTable("Topologies");
                });

            modelBuilder.Entity("BenchmarkModelTaskModel", b =>
                {
                    b.HasOne("Elpida.Backend.Data.Abstractions.Models.BenchmarkModel", null)
                        .WithMany()
                        .HasForeignKey("BenchmarksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Elpida.Backend.Data.Abstractions.Models.Task.TaskModel", null)
                        .WithMany()
                        .HasForeignKey("TasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Elpida.Backend.Data.Abstractions.Models.Result.ResultModel", b =>
                {
                    b.HasOne("Elpida.Backend.Data.Abstractions.Models.BenchmarkModel", "Benchmark")
                        .WithMany()
                        .HasForeignKey("BenchmarkId");

                    b.HasOne("Elpida.Backend.Data.Abstractions.Models.Topology.TopologyModel", "Topology")
                        .WithMany()
                        .HasForeignKey("TopologyId");

                    b.Navigation("Benchmark");

                    b.Navigation("Topology");
                });

            modelBuilder.Entity("Elpida.Backend.Data.Abstractions.Models.Result.TaskResultModel", b =>
                {
                    b.HasOne("Elpida.Backend.Data.Abstractions.Models.Result.ResultModel", "Result")
                        .WithMany("TaskResults")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Elpida.Backend.Data.Abstractions.Models.Task.TaskModel", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId");

                    b.Navigation("Result");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Elpida.Backend.Data.Abstractions.Models.Topology.TopologyModel", b =>
                {
                    b.HasOne("Elpida.Backend.Data.Abstractions.Models.Cpu.CpuModel", "Cpu")
                        .WithMany()
                        .HasForeignKey("CpuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cpu");
                });

            modelBuilder.Entity("Elpida.Backend.Data.Abstractions.Models.Result.ResultModel", b =>
                {
                    b.Navigation("TaskResults");
                });
#pragma warning restore 612, 618
        }
    }
}
