// <auto-generated />
using System;
using Elpida.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Elpida.Backend.Migrations
{
    [DbContext(typeof(ElpidaContext))]
    partial class ElpidaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("BenchmarkModelTaskModel", b =>
                {
                    b.Property<long>("BenchmarksId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TasksId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BenchmarksId", "TasksId");

                    b.HasIndex("TasksId");

                    b.ToTable("BenchmarkModelTaskModel");
                });

            modelBuilder.Entity("Elpida.Backend.Data.Abstractions.Models.BenchmarkModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Benchmarks");
                });

            modelBuilder.Entity("Elpida.Backend.Data.Abstractions.Models.Cpu.CpuModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Caches")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Smt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cpus");
                });

            modelBuilder.Entity("Elpida.Backend.Data.Abstractions.Models.ElpidaModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompilerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompilerVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionBuild")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VersionMajor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VersionMinor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VersionRevision")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Elpidas");
                });

            modelBuilder.Entity("Elpida.Backend.Data.Abstractions.Models.OsModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Oses");
                });

            modelBuilder.Entity("Elpida.Backend.Data.Abstractions.Models.Result.BenchmarkResultModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Affinity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("BenchmarkId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ElpidaId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("JoinOverhead")
                        .HasColumnType("REAL");

                    b.Property<double>("LockOverhead")
                        .HasColumnType("REAL");

                    b.Property<double>("LoopOverhead")
                        .HasColumnType("REAL");

                    b.Property<long>("MemorySize")
                        .HasColumnType("INTEGER");

                    b.Property<double>("NotifyOverhead")
                        .HasColumnType("REAL");

                    b.Property<double>("NowOverhead")
                        .HasColumnType("REAL");

                    b.Property<long>("OsId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PageSize")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SleepOverhead")
                        .HasColumnType("REAL");

                    b.Property<double>("TargetTime")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<long>("TopologyId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WakeupOverhead")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("BenchmarkId");

                    b.HasIndex("ElpidaId");

                    b.HasIndex("OsId");

                    b.HasIndex("TopologyId");

                    b.ToTable("BenchmarkResults");
                });

            modelBuilder.Entity("Elpida.Backend.Data.Abstractions.Models.Result.TaskResultModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BenchmarkResultId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CpuId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("InputSize")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MarginOfError")
                        .HasColumnType("REAL");

                    b.Property<double>("Max")
                        .HasColumnType("REAL");

                    b.Property<double>("Mean")
                        .HasColumnType("REAL");

                    b.Property<double>("Min")
                        .HasColumnType("REAL");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SampleSize")
                        .HasColumnType("INTEGER");

                    b.Property<double>("StandardDeviation")
                        .HasColumnType("REAL");

                    b.Property<long>("TaskId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Tau")
                        .HasColumnType("REAL");

                    b.Property<double>("Time")
                        .HasColumnType("REAL");

                    b.Property<long>("TopologyId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("BenchmarkResultId");

                    b.HasIndex("CpuId");

                    b.HasIndex("TaskId");

                    b.HasIndex("TopologyId");

                    b.ToTable("TaskResults");
                });

            modelBuilder.Entity("Elpida.Backend.Data.Abstractions.Models.Statistics.TaskStatisticsModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CpuId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MarginOfError")
                        .HasColumnType("REAL");

                    b.Property<double>("Max")
                        .HasColumnType("REAL");

                    b.Property<double>("Mean")
                        .HasColumnType("REAL");

                    b.Property<double>("MeanTime")
                        .HasColumnType("REAL");

                    b.Property<double>("Min")
                        .HasColumnType("REAL");

                    b.Property<long>("SampleSize")
                        .HasColumnType("INTEGER");

                    b.Property<double>("StandardDeviation")
                        .HasColumnType("REAL");

                    b.Property<long>("TaskId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Tau")
                        .HasColumnType("REAL");

                    b.Property<long>("TopologyId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalDeviation")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalTime")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalValue")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CpuId");

                    b.HasIndex("TaskId");

                    b.HasIndex("TopologyId");

                    b.ToTable("TaskStatistics");
                });

            modelBuilder.Entity("Elpida.Backend.Data.Abstractions.Models.Task.TaskModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InputDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputName")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputProperties")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputUnit")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputName")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputProperties")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputUnit")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResultAggregation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResultType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultUnit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Elpida.Backend.Data.Abstractions.Models.Topology.TopologyModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CpuId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Root")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TopologyHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalDepth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalLogicalCores")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPhysicalCores")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CpuId");

                    b.ToTable("Topologies");
                });

            modelBuilder.Entity("BenchmarkModelTaskModel", b =>
                {
                    b.HasOne("Elpida.Backend.Data.Abstractions.Models.BenchmarkModel", null)
                        .WithMany()
                        .HasForeignKey("BenchmarksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Elpida.Backend.Data.Abstractions.Models.Task.TaskModel", null)
                        .WithMany()
                        .HasForeignKey("TasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Elpida.Backend.Data.Abstractions.Models.Result.BenchmarkResultModel", b =>
                {
                    b.HasOne("Elpida.Backend.Data.Abstractions.Models.BenchmarkModel", "Benchmark")
                        .WithMany()
                        .HasForeignKey("BenchmarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Elpida.Backend.Data.Abstractions.Models.ElpidaModel", "Elpida")
                        .WithMany()
                        .HasForeignKey("ElpidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Elpida.Backend.Data.Abstractions.Models.OsModel", "Os")
                        .WithMany()
                        .HasForeignKey("OsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Elpida.Backend.Data.Abstractions.Models.Topology.TopologyModel", "Topology")
                        .WithMany()
                        .HasForeignKey("TopologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benchmark");

                    b.Navigation("Elpida");

                    b.Navigation("Os");

                    b.Navigation("Topology");
                });

            modelBuilder.Entity("Elpida.Backend.Data.Abstractions.Models.Result.TaskResultModel", b =>
                {
                    b.HasOne("Elpida.Backend.Data.Abstractions.Models.Result.BenchmarkResultModel", "BenchmarkResult")
                        .WithMany("TaskResults")
                        .HasForeignKey("BenchmarkResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Elpida.Backend.Data.Abstractions.Models.Cpu.CpuModel", "Cpu")
                        .WithMany()
                        .HasForeignKey("CpuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Elpida.Backend.Data.Abstractions.Models.Task.TaskModel", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Elpida.Backend.Data.Abstractions.Models.Topology.TopologyModel", "Topology")
                        .WithMany()
                        .HasForeignKey("TopologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BenchmarkResult");

                    b.Navigation("Cpu");

                    b.Navigation("Task");

                    b.Navigation("Topology");
                });

            modelBuilder.Entity("Elpida.Backend.Data.Abstractions.Models.Statistics.TaskStatisticsModel", b =>
                {
                    b.HasOne("Elpida.Backend.Data.Abstractions.Models.Cpu.CpuModel", "Cpu")
                        .WithMany("TaskStatistics")
                        .HasForeignKey("CpuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Elpida.Backend.Data.Abstractions.Models.Task.TaskModel", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Elpida.Backend.Data.Abstractions.Models.Topology.TopologyModel", "Topology")
                        .WithMany()
                        .HasForeignKey("TopologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cpu");

                    b.Navigation("Task");

                    b.Navigation("Topology");
                });

            modelBuilder.Entity("Elpida.Backend.Data.Abstractions.Models.Topology.TopologyModel", b =>
                {
                    b.HasOne("Elpida.Backend.Data.Abstractions.Models.Cpu.CpuModel", "Cpu")
                        .WithMany("Topologies")
                        .HasForeignKey("CpuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cpu");
                });

            modelBuilder.Entity("Elpida.Backend.Data.Abstractions.Models.Cpu.CpuModel", b =>
                {
                    b.Navigation("TaskStatistics");

                    b.Navigation("Topologies");
                });

            modelBuilder.Entity("Elpida.Backend.Data.Abstractions.Models.Result.BenchmarkResultModel", b =>
                {
                    b.Navigation("TaskResults");
                });
#pragma warning restore 612, 618
        }
    }
}
